spring:
  application:
    name: servidor-gateway   
  cloud: 
   gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"   
      routes:
      - id: servCursos #Id de la ruta 
        uri: lb://servicio-cursos
        predicates:
          - Path=/scursos/** #Cuando Gateway detecte que en la peticion URL venga este path, enrutará la peticion hacia el servicio indicado en la propiedad "uri" (lb://servicio-cursos)
        filters:
          - RewritePath=/scursos/*, /cursos/ #Lo que indica es que a la url indicada en la propiedad "uri", se le adicionará un "/" mas todo lo que venga despues de "scursos" en la petición URL de entrada
          
      - id: servFormacion
        uri: lb://cliente-formacion
        predicates:
          - Path=/sformacion/**
        filters:
          - RewritePath=/sformacion/*, /formacion/
server:
  port: 7000
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka




